apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployement
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
          - name: phpmyadmin
            image: phpmyadmin
            imagePullPolicy: Never
            ports:
                - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: lb-phpmyadmin
  annotations:
      metallb.universe.tf/allow-shared-ip: wp
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.10
  ports:
  - port: 5000
    name: phpmyadmin
    protocol: TCP
    targetPort: 5000
  selector:
    app: phpmyadmin
