apiVersion: apps/v1

kind: Deployment
metadata:
    name: ftps-deployment
    labels:
        app   : ftps
spec:
    replicas: 1
    selector:
        matchLabels:
            project: ftps
    template:
        metadata:
            labels:
                project: ftps
        spec:
            containers:
                - name: ftps
                  image: ftps
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 21
                      - containerPort: 21000
                  livenessProbe:
                    exec:
                        command:
                        - sh
                        - /tmp/healthy.sh
                    initialDelaySeconds: 14
                    periodSeconds: 5
---
apiVersion: v1

kind: Service
metadata:
    name: service-ftps
    annotations:
        metallb.universe.tf/allow-shared-ip: wp
    labels:
        app: ftps
        env: ft_services
spec:
    selector:
        project: ftps
    ports:
        - name: ftps
          port: 21 
        - name: ftpsd0
          port: 21000
    type: LoadBalancer
    loadBalancerIP: 192.168.99.10
