apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
          livenessProbe:
            exec:
                command:
                - sh
                - /tmp/healthy.sh
            initialDelaySeconds: 8
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.10
  ports:
    - port: 5050
      name: http
      protocol: TCP
      targetPort: 5050
        # 셀렉터에 해당하는 라벨로트래픽을 보내준다.
        #  targetport는 특정포드로 접근하기 위핸 포트 넘버, (deployment 에서 설정한 pod의 포트 넘버) 
  selector:
    app: wordpress
